### ISSUE TITLE
Refactor config.pl and probe.pl generation.

### ISSUE THREAD

**Issue by plicease** [Perl5-FFI/FFI-Platypus#110]
- `config.pl` should have only the things that are useful at FFI-Platypus + FFI module runtime, like type size/sign/alignment.
 - `probe.pl` should have only the things that are useful during a FFI module probe, like header files, abi, etc. and preferably not stuff that is only useful during the Platypus probe, like `eumm`

There is some duplication, some stuff is in `probe.pl` AND `config.pl`, although in a different form.  This duplication should be removed.

Beyond being more correct, the motivation for removing `eumm` from `probe.pl` is to avoid including non-reproducible build information into the install files in a Debian install, see #104.

**Comment by plicease** [comment]
@gregoa this has been implemented as #159 and released as `FFI::Platypus` 0.95_03.  I removed a number of keys that weren't being used and/or moved anything build related into its own store.  You may want to check that this version addresses the concern that you originally raised in #104.

**Comment by gregoa** [comment]
(Sorry for the delay …)

Indeed, this seems to be fixed in 0.96 - no more diff between the built packages after building them with different paths (and after removing my hack to replace the paths :)). Thank you!
