### ISSUE TITLE
Dealing with pointer to a record as return value

### ISSUE THREAD

**Issue by rabbiveesh** [Perl5-FFI/FFI-Platypus#186]
I'm having a problem. I'm not exactly sure what's intended for me to do. I'm using this function:
```C
LIBPOSTAL_EXPORT libpostal_address_parser_response_t *
libpostal_parse_address(char *address, libpostal_address_parser_options_t options);
```
which returns this struct:
```C
typedef struct libpostal_address_parser_response {
    size_t num_components;
    char **components;
    char **labels;
} libpostal_address_parser_response_t;

typedef libpostal_address_parser_response_t libpostal_parsed_address_components_t;
```

And in perl, I'm binding it like this:
```perl
$ffi->attach( [ libpostal_get_address_parser_default_options => 'parser_defaults' ],
   [], 'parser_options');

$ffi->attach( [ libpostal_address_parser_response_destroy => 'destroy_parsings' ],
   [ 'parser_response*' ], 'void');


$ffi->attach( [ libpostal_parse_address => 'parse_address' ],
  [ 'string', 'parser_options' ], 'parser_response*',
  sub {
    my ($inner, @args) = @_;
    #lazy load the parser
    $parser_loaded = 
      $ffi->function( libpostal_setup_parser => [], 'bool')->call
      unless $parser_loaded;
    
    #make the options arg optional
    push @args, parser_defaults() if @args == 1;
    my $ret = $inner->(@args);
    #extract the results
    my $len = $ret->num_conmponents;
    my $labels = $ffi->cast( 'opaque', "string[$len]", $ret->labels);
    my $values = $ffi->cast( 'opaque', "string[$len]", $ret->components);
    #destroy_parsings($ret);
    #make it a hashref for the return
    return { map { ($labels->[$_] => $values->[$_] ) } 0..$len-1 };
  }
);
```
Basically, it's returning a pointer to a struct which contains two arrays of strings. The API clearly expects me to free the struct once I extract the data from it (based on the python and old XS implementation of the library). 

Now, when I free it myself (uncommenting the `destroy_parsings` line), I get a double-free memory corruption error. When I don't free it, I get a memory leak. And, when I tried switching the return type to opaque and casting it into the record, it returns garbage values.

Just for the record, I'm using api => 1.

What should I be doing in this situation?  If you want a fuller look at the code, you can see my repo at https://github.com/rabbiveesh/FFI-Postal.

**Comment by rabbiveesh** [comment]
Oh, I realized that I needed to cast the opaque to `parser_response*` rather than just `parser_response`. That eliminates the memory leak, and allows me to safely free the pointer.

I saw in the docs that the approach of returning opaque, then casting and freeing, is suggested for strings. Could you update that to mention returned pointers in general? I had a little bit of a run around with this.

**Comment by plicease** [comment]
Good point.  I've added a note to #184 which is going to be the big documentation update for 1.00.
