### ISSUE TITLE
Documentation issue. Cross reference on enums

### ISSUE THREAD

**Issue by KES777** [Perl5-FFI/FFI-Platypus#198]
Documentation on [page](https://metacpan.org/pod/FFI::Platypus::Type#Enum-types) has:
>See the main FAQ ("FAQ" in FFI::Platypus) for details on the best way to specify value constants when there are lots of possible values.

But FAQ in FFI::Platypus gives just reference  back:
>For more details on enumerated types see "Enum types" in FFI::Platypus::Type.

So documentation just links each other page and does not describe details/best way to describe enum

**Comment by KES777** [comment]
>https://metacpan.org/pod/FFI::Platypus::Type#Records
```
package My::UnixTime;
 
use FFI::Platypus::Record;
 
record_layout(qw(
    int    tm_sec
    int    tm_min
    int    tm_hour
    int    tm_mday
    int    tm_mon
    int    tm_year
    int    tm_wday
    int    tm_yday
    int    tm_isdst
    long   tm_gmtoff
    string tm_zone
));
 
my $ffi = FFI::Platypus->new( api => 1 );```

probably here should be `record_layout_1`, because you use `api => 1` but declare record with api 0

**Comment by KES777** [comment]
https://metacpan.org/pod/FFI::Platypus::Type#Example-2:-Blessed-references

>I good example of a C library that uses this pattern, including inheritance is libarchive

**Comment by plicease** [comment]
I've reworded the enum sections to hopefully be more helpful.  There isn't really a "best" way to import constant values just trade offs.
