### ISSUE TITLE
Please provide an example how to create records

### ISSUE THREAD

**Issue by mnbv09870987** [Perl5-FFI/FFI-Platypus#205]
Hi. I am using SDL and want to run next code:
```
    SDL_SetRenderDrawColor(ren, 0x00, 0x00, 0x00, 0x00);
    SDL_RenderClear(ren);
    SDL_SetRenderDrawColor(ren, 0xFF, 0xFF, 0xFF, 0xFF);

    SDL_Rect rect1 = {10, 10, 50, 50};
    SDL_RenderFillRect(ren, &rect1);
```

The `SDL_Rect` is defined as next:
```
typedef struct SDL_Rect
{
    int x, y;
    int w, h;
} SDL_Rect;
```

How can I define `SDL_Rect` in perl so I can call:

    SDL_RenderFillRect( $ren, SDL_Rect([ 10, 10, 50, 50 ]) )

**Comment by plicease** [comment]
What you want is `FFI::Platypus::Record`.  Something along the lines of this totally untested code:

```perl
package SDLRect {
  use FFI::Platypus::Record;
  record_layout_1(qw(
    int x
    int y
    int w
    int h
  ));
}
$ffi->attach( SDL_RenderFillRect => [ 'opaque', 'record(SDLRect)*' ] => 'int' );

my $rec = SDLRect->new( x => 10, y => 10, w => 50, h => 50 );
SDL_RenderFillRect( $ren, $rec );
```

If you are using the old `api => 0` (not recommended) then the type would be `record(SDLRect)`.

There is a working example here:
https://metacpan.org/pod/FFI::Platypus#structured-data-records
