### ISSUE TITLE
Warnings in FFI::Platypus::TypeParser

### ISSUE THREAD

**Issue by Chayyoo** [Perl5-FFI/FFI-Platypus#213]
Name "FFI::Platypus::TypeParser::ffi_type" used only once: possible typo at /usr/share/perl/5.24/XSLoader.pm line 114.
Name "FFI::Platypus::TypeParser::basic_type" used only once: possible typo at /usr/share/perl/5.24/XSLoader.pm line 114.

Something to worry about?

**Comment by plicease** [comment]
Huh.  It's probably fine, but can you detail exactly how you are using it?  I'm not able to reproduce those warnings:

```
$ perl -Mblib -w lib/FFI/Platypus/TypeParser.pm
$
```

**Comment by Chayyoo** [comment]
It looks like there's something wrong with my perl setup:$ perl -Mblib -w /usr/local/lib/x86_64-linux-gnu/perl/5.24.1/FFI/Platypus/TypeParser.pm
Cannot find blib even in /home/bt/../../../../..
BEGIN failed--compilation aborted.

While I have blib in:/usr/share/perl/5.24.1/blib.pm
Otherwise the script runs fine. Nothing special really, it begins like:#!/usr/bin/perl -w
use utf8;
use Encode;
use FFI::Platypus;
my $ffi = FFI::Platypus->new(api => 0, lib => "./platypus/funksies.so", lang => 'C');
$ffi->attach(schrap_stopwoorden => ['string','string'] => 'string');

and then somewhere down I use the exported function:$term = decode("utf8", schrap_stopwoorden (encode("utf8",$term), $lang));

It runs a bit slower than the Inline C version (15 seconds versus 12).
    On Tuesday, 31 December 2019, 13:55:04 CET, Graham✈️✈️ <notifications@github.com> wrote:  
 
 
Huh. It's probably fine, but can you detail exactly how you are using it? I'm not able to reproduce those warnings:
$ perl -Mblib -w lib/FFI/Platypus/TypeParser.pm
$

**Comment by plicease** [comment]
Ah.  I recommend that you remove `-w` from the shebang line and instead use scoped warnings/strict for your scripts/modules:

```perl
#!/usr/bin/perl
use strict;
use warnings;
...
```

The problem with `-w` is that it is global and it will turn on warnings for all modules that you use, some of which are specifically designed to not have warnings turned on in whole or in part.
