### ISSUE TITLE
Calling Go functions from Perl

### ISSUE THREAD

**Issue by Chayyoo** [Perl5-FFI/FFI-Platypus#215]
I'm trying to call Go(lang) functions from Perl with FFI::Platypus. It works well with numerical parameters. As an example, I can call the following Go code:

```go
package main
import "C"
import "math"

//export Add
func Add(a, b int) int {
	return a + b
}

//export Cosine
func Cosine(x float64) float64 {
	return math.Cos(x)
}

func main() {}
```

compile it with:
`go build -buildmode c-shared -o sample.so sample.go`
and call it with:

```perl
#!/usr/bin/perl
use FFI::Platypus;
my $ffi = FFI::Platypus->new(api => 0, lib => "./sample.so", lang => 'C');
$ffi->attach(Add => ['int','int'] => 'int');
$ffi->attach(Cosine => ['double'] => 'double');
print Add(3,5), "\n";
print Cosine(1), "\n";
```
However, passing strings around doesn't work. Any idea how it could me made to work?
In the file `sample.h` strings are defined with:
`typedef struct { const char *p; GoInt n; } GoString;
`

**Comment by plicease** [comment]
The Go language plugin is now released to cpan 🎉 
Please feel free to open issues/PRs there if you have questions:
https://github.com/Perl5-FFI/FFI-Platypus-Lang-Go
https://metacpan.org/pod/release/PLICEASE/FFI-Platypus-Lang-Go-0.01/lib/FFI/Platypus/Lang/Go.pm

I hope to improve the documentation there over time.

**Comment by b03cmans** [comment]
Hi @plicease 

i am trying to call the below golang func from the documention that you provided on Metacpan

//export Sort
func Sort(vals []int) { sort.Ints(vals) }

any idea how i can attach it like the other functions on the example ?

**Comment by plicease** [comment]
@b03cmans can you open a new ticket against FFI-Platypus-Lang-Go here:
https://github.com/perl5-FFI/FFI-Platypus-Lang-Go/issues
